- name: installing java
  become: true
  shell: sudo apt install openjdk-8-jdk -y
- name: installing maven
  become: true
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - maven